import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowLeft,faCheck } from "@fortawesome/free-solid-svg-icons";
import DetailActions from "@/components/DetailActions";
import { fallbackWorkouts,getWorkout } from "@/lib/workouts";

export async function generateStaticParams(){return fallbackWorkouts.map(w=>({id:String(w.id)}));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const workout=await getWorkout((await params).id);return {title:workout?.name||"Workout not found",description:workout?.description};}
export default async function WorkoutDetails({params}:{params:Promise<{id:string}>}){const workout=await getWorkout((await params).id);if(!workout)notFound();const specs=[["Equipment",workout.equipment],["Difficulty",workout.difficulty],["Sets",workout.sets],["Reps",workout.reps],["Duration",`${workout.duration} min`],["Calories",`${workout.caloriesBurned} kcal`],["Rating",workout.rating]];return <section className="py-10 md:py-16"><div className="container-shell"><Link href="/#library" className="mb-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#9ca199] hover:text-[#c9ff38]"><FontAwesomeIcon icon={faArrowLeft}/>Back to library</Link><div className="grid gap-10 lg:grid-cols-[.95fr_1.05fr] lg:gap-16"><div className="relative min-h-[460px] overflow-hidden border border-[#30332f] bg-[#20231f] lg:sticky lg:top-28 lg:h-[680px]"><Image src={workout.image} alt={workout.name} fill priority sizes="(max-width:1024px) 100vw,50vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"/><span className="absolute bottom-5 left-5 border bg-black/70 px-3 py-2 text-xs font-bold uppercase tracking-widest backdrop-blur">{workout.difficulty}</span></div><div><div className="flex flex-wrap gap-2">{workout.muscleGroups.map(tag=><span className="tag" key={tag}>{tag}</span>)}</div><h1 className="mt-5 text-[clamp(3rem,7vw,6rem)] font-bold uppercase leading-[.9] tracking-[-.04em]">{workout.name}</h1><p className="my-7 max-w-2xl text-lg leading-8 text-[#aeb3ab]">{workout.description}</p><DetailActions workout={workout}/><div className="mt-10 border border-[#30332f] bg-[#131513]"><h2 className="border-b border-[#30332f] px-5 py-4 text-sm font-bold uppercase tracking-[.16em] lime">Key specs</h2><div className="grid sm:grid-cols-2">{specs.map(([label,value],i)=><div key={String(label)} className={`flex justify-between gap-4 border-[#30332f] px-5 py-4 ${i<specs.length-2?'border-b':''} ${i%2===0?'sm:border-r':''}`}><span className="text-xs font-bold uppercase tracking-widest text-[#777c75]">{label}</span><span className="text-right text-sm font-semibold">{value}</span></div>)}</div></div><div className="mt-10"><h2 className="mb-5 text-2xl font-semibold uppercase">Instructions</h2><ol className="space-y-3">{workout.instructions.map((step,i)=><li key={step} className="flex gap-4 border border-[#2c2f2b] bg-[#131513] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center bg-[#c9ff38] text-sm font-extrabold text-black">{i+1}</span><p className="pt-1 text-sm leading-6 text-[#c4c8c1]">{step}</p><FontAwesomeIcon icon={faCheck} className="ml-auto mt-2 text-xs text-[#596054]"/></li>)}</ol></div></div></div></div></section>}
