"use client";
import { Suspense,useEffect,useMemo,useState } from "react";
import { useSearchParams } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheck,faDumbbell,faFire,faMagnifyingGlass,faStopwatch,faXmark } from "@fortawesome/free-solid-svg-icons";
import { usePlan } from "@/context/PlanContext";
import Stats from "./Stats";

function PlanContent(){
  const params=useSearchParams(); const {plan,saved,hydrated,markDone,removeFromPlan,removeFromSaved}=usePlan();
  const [tab,setTab]=useState<"plan"|"saved">(params.get("tab")==="saved"?"saved":"plan"); const [query,setQuery]=useState("");
  useEffect(()=>{if(params.get("tab")==="saved")setTab("saved")},[params]);
  const items=(tab==="plan"?plan:saved).filter(w=>`${w.name} ${w.muscleGroups.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const metrics=useMemo(()=>({exercises:plan.length,minutes:plan.reduce((s,w)=>s+w.duration,0),calories:plan.reduce((s,w)=>s+w.caloriesBurned,0)}),[plan]);
  if(!hydrated)return <div className="grid min-h-[50vh] place-items-center"><p className="animate-pulse uppercase tracking-widest text-[#a4a9a1]">Loading workouts…</p></div>;
  return <div className="container-shell py-14 md:py-20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold tracking-[.25em] lime">YOUR TRAINING LOG</p><h1 className="section-title">MY PLAN</h1><p className="mt-3 text-[#9ca199]">Cap of five lifts for today. Finish them, then load more.</p></div><label className="flex h-11 items-center gap-2 border border-[#343833] bg-[#121412] px-4"><FontAwesomeIcon icon={faMagnifyingGlass} className="text-[#747a71]"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search your workouts" placeholder="Search your workouts" className="bg-transparent text-sm outline-none"/></label></div>
  <div className="my-10 grid gap-3 sm:grid-cols-3">{[["Exercises",metrics.exercises,faDumbbell],["Minutes",metrics.minutes,faStopwatch],["Calories",metrics.calories,faFire]].map(([label,value,icon])=><div key={String(label)} className="border border-[#30332f] bg-[#151716] p-5"><FontAwesomeIcon icon={icon as never} className="mb-5 text-xl lime"/><p className="display text-4xl font-semibold">{value as number}</p><p className="mt-1 text-xs font-bold uppercase tracking-widest text-[#888d86]">{label as string}</p></div>)}</div>
  <div className="mb-6 flex border-b border-[#30332f]"><button onClick={()=>setTab("plan")} className={`px-5 py-4 text-xs font-bold uppercase tracking-widest ${tab==='plan'?'border-b-2 border-[#c9ff38] text-[#c9ff38]':'text-[#858a82]'}`}>Today&apos;s Plan <span className="ml-1">{plan.length}</span></button><button onClick={()=>setTab("saved")} className={`px-5 py-4 text-xs font-bold uppercase tracking-widest ${tab==='saved'?'border-b-2 border-[#c9ff38] text-[#c9ff38]':'text-[#858a82]'}`}>Saved <span className="ml-1">{saved.length}</span></button></div>
  {items.length?<div className="space-y-3">{items.map(workout=><article key={workout.id} className={`grid items-center gap-5 border border-[#30332f] bg-[#151716] p-3 sm:grid-cols-[130px_1fr_auto] ${(workout as {done?:boolean}).done?'opacity-55':''}`}><div className="relative aspect-[4/3] overflow-hidden bg-[#242724]"><Image src={workout.image} alt={workout.name} fill sizes="130px" className="object-cover"/>{(workout as {done?:boolean}).done&&<span className="absolute inset-0 grid place-items-center bg-black/50 text-3xl lime"><FontAwesomeIcon icon={faCheck}/></span>}</div><div><div className="flex flex-wrap gap-1.5">{workout.muscleGroups.map(t=><span className="tag" key={t}>{t}</span>)}</div><h2 className={`mt-2 text-xl font-semibold uppercase ${(workout as {done?:boolean}).done?'line-through':''}`}>{workout.name}</h2><p className="mb-3 mt-1 text-sm text-[#8e938b]">{workout.equipment}</p><Stats duration={workout.duration} calories={workout.caloriesBurned} rating={workout.rating}/></div><div className="flex flex-wrap gap-2 sm:max-w-[170px] sm:justify-end"><Link href={`/workouts/${workout.id}`} className="btn btn-ghost !min-h-9 !px-3 !py-1 text-[10px]">View Details</Link>{tab==='plan'&&<button onClick={()=>markDone(workout.id)} className="btn btn-ghost !min-h-9 !px-3 !py-1 text-[10px]"><FontAwesomeIcon icon={faCheck}/>{(workout as {done?:boolean}).done?'Undo':'Mark as Done'}</button>}<button aria-label={`Remove ${workout.name}`} onClick={()=>tab==='plan'?removeFromPlan(workout.id):removeFromSaved(workout.id)} className="grid h-9 w-9 place-items-center border border-[#553531] text-[#ff7967] hover:bg-[#331a17]"><FontAwesomeIcon icon={faXmark}/></button></div></article>)}</div>:<div className="border border-dashed border-[#3b3f39] px-5 py-20 text-center"><FontAwesomeIcon icon={faDumbbell} className="text-4xl text-[#464b44]"/><h2 className="mt-5 text-3xl font-semibold uppercase">Nothing here yet</h2><p className="mx-auto mt-3 max-w-md text-[#949990]">{query?"No workouts match your search.":"Browse the library and add a lift to get today moving."}</p><Link href="/#library" className="btn btn-primary mt-6">Go to workouts</Link></div>}
  </div>
}
export default function PlanPage(){return <Suspense fallback={<div className="grid min-h-[60vh] place-items-center">Loading workouts…</div>}><PlanContent/></Suspense>}
